apiVersion: v1
kind: ReplicationController
metadata:
  name: webapp
  labels:
    name: webapp
spec:
  replicas: 1
  selector: 
    name: webapp
  template:
    metadata:
      labels:
        name: webapp
    spec:
      containers:
      - name: webapp
        image: maxwell/webapp:v1.0.0
        ports:
        - containerPort: 9999 
